SESSION_PERMANENT = False
SESSION_TYPE = "filesystem"
TEMPLATES_AUTO_RELOAD = True
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT= 465
MAIL_USERNAME = 'cdozcodeprojects@gmail.com'
MAIL_PASSWORD= 'chimchid8912'
MAIL_USE_TLS= False
MAIL_USE_SSL = True
SECRET_KEY = 'the key'
